### PR TITLE
Use writable URL when cloning map repos

### PR DESCRIPTION
**Pull request by ssoloff**
The Git protocol does not support authentication, and thus cannot be used to push changes back to GitHub.  I ran into this recently while trying to mass update all triplea-maps repos.  After committing the changes, all of my pushes failed because the repos were cloned using `git:` URLs, which are not writable on GitHub.  This PR modifies the _clone\_all.sh_ script to clone all repos using the SSH protocol, which does permit changes to be pushed back to GitHub (assuming the user has registered their SSH key with GitHub).

I also removed some unnecessary trailing semi-colons and whitespace.

@DanVanAtta Please let me know if I missed something obvious here.  I would have assumed someone trying to do a mass update would have run into this problem before using the _clone\_all.sh_ script.

### CODE REVIEW

**Comment by ssoloff** [comment]
@DanVanAtta Bumping...

**Comment by DanVanAtta** [comment]
Hmm, I'm not sure if I've run into this, curious where the difference would be. Could you clarify by 'writable' @ssoloff ? Do you not have 'push' permissions?

I don't know if I"ve ever used a non `git:` URL to clone a map, hence the curiosity

**Comment by ssoloff** [comment]
@DanVanAtta 

Using a `git:` URI:

<pre>
$ <b>git clone git://github.com/triplea-maps/tutorial.git</b>
Cloning into 'tutorial'...
remote: Counting objects: 4111, done.
remote: Total 4111 (delta 0), reused 0 (delta 0), pack-reused 4111
Receiving objects: 100% (4111/4111), 44.69 MiB | 3.41 MiB/s, done.
Resolving deltas: 100% (621/621), done.
$ <b>cd tutorial/</b>
$ <b>git checkout -b git-uri-push-test</b>
Switched to a new branch 'git-uri-push-test'
$ <b>touch test.txt</b>
$ <b>git add test.txt</b>
$ <b>git commit -m "Test"</b>
[git-uri-push-test 66ad21e] Test
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 test.txt
$ <b>git push --set-upstream origin git-uri-push-test</b>
fatal: remote error: 
  You can't push to git://github.com/triplea-maps/tutorial.git
  Use https://github.com/triplea-maps/tutorial.git
</pre>

Using a `ssh:` URI:

<pre>
$ <b>git clone git@github.com:triplea-maps/tutorial.git</b>
Cloning into 'tutorial'...
remote: Counting objects: 4111, done.
remote: Total 4111 (delta 0), reused 0 (delta 0), pack-reused 4111
Receiving objects: 100% (4111/4111), 44.69 MiB | 3.29 MiB/s, done.
Resolving deltas: 100% (621/621), done.
$ <b>cd tutorial/</b>
$ <b>git checkout -b git-uri-push-test</b>
Switched to a new branch 'git-uri-push-test'
$ <b>touch test.txt</b>
$ <b>git add test.txt</b>
$ <b>git commit -m "Test"</b>
[git-uri-push-test ffb85bc] Test
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 test.txt
$ <b>git push --set-upstream origin git-uri-push-test</b>
Counting objects: 3, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 656 bytes | 656.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To github.com:triplea-maps/tutorial.git
 * [new branch]      git-uri-push-test -> git-uri-push-test
Branch git-uri-push-test set up to track remote branch git-uri-push-test from origin.
</pre>

**Comment by ssoloff** [comment]
> I don't know if I"ve ever used a non `git:` URL to clone a map, hence the curiosity

You may be confusing a URL that uses the `git` scheme vs. a URL that uses the `ssh` scheme with a user named `git`.  Git supports the SSH protocol using either an URL with the `ssh` scheme or an `scp`-like syntax.  For example, the following `ssh` URL:

```
ssh://git@github.com/triplea-maps/tutorial.git
```

can also be specified using the following `scp`-like syntax:

```
git@github.com:triplea-maps/tutorial.git
```

GitHub typically displays the latter instead of the former, so it's easy to see the `git` username at the beginning and interpret it as a `git` URL.

**Comment by ssoloff** [comment]
@DanVanAtta Bumping this since the affected script is being moved to a new repo.  Do you want to finish our discussion here, or would you rather I just close this PR now and re-open it over in triplea-maps/admin_scripts?

**Comment by DanVanAtta** [comment]
https://github.com/triplea-maps/admin_scripts/pull/2

**Pull request closed without merging**
